spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/msa
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      show_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0