spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: 10800000

server:
  port: 19095